# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_user_conf_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='container_id',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
