LIDI_FILES_DIR=$1/lidi_files;
LIDI_FILES_PROBLEMS=$LIDI_FILES_DIR/problems;
LIDI_FILES_PROBLEMS_TMP=$LIDI_FILES_PROBLEMS/tmp;
LIDI_FILES_TESTCASES=$LIDI_FILES_DIR/testcases;
LIDI_FILES_TESTCASES_SOL=$LIDI_FILES_TESTCASES/solutions;
LIDI_FILES_SOLUTIONS=$LIDI_FILES_DIR/solutions;
LIDI_FILES_UPLOADED=$LIDI_FILES_DIR/uploaded;
LIDI_FILES_UPLOADED_BIN=$LIDI_FILES_UPLOADED/bin;

export LIDI_FILES_DIR;
export LIDI_FILES_PROBLEMS;
export LIDI_FILES_PROBLEMS_TMP;
export LIDI_FILES_TESTCASES;
export LIDI_FILES_TESTCASES_SOL;
export LIDI_FILES_SOLUTIONS;
export LIDI_FILES_UPLOADED;
export LIDI_FILES_UPLOADED_BIN;
