# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.CharField(default=b'2017/6/4', max_length=10),
        ),
    ]
