# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20170604_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='is_solved',
        ),
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.IntegerField(default=-1),
        ),
    ]
