# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20170604_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='tries_until_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.CharField(default=b'2017/6/5', max_length=10),
        ),
        migrations.AlterField(
            model_name='submission',
            name='tries',
            field=models.IntegerField(default=0),
        ),
    ]
