# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_auto_20180522_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.CharField(default=b'2018/5/24', max_length=10),
        ),
    ]
